// Автозгенеровано tools/gen_seed.py — вбудована колода для ОФЛАЙН-гри (без сервера/БД).
// Ті самі дані, що й у apps/web/db/seed.sql. НЕ редагувати вручну — правити в gen_seed.py.
export type Situation = { id: number; text_ua: string; text_ru: string }
export type MemeCard = { id: number; title: string; image_url: string }

export const SITUATIONS: Situation[] = [
  { id: 1, text_ua: "Коли о третій ночі ти відкриваєш холодильник у п'ятий раз...", text_ru: "Когда в три ночи ты открываешь холодильник в пятый раз..." },
  { id: 2, text_ua: "Мій настрій в понеділок о 9 ранку", text_ru: "Моё настроение в понедельник в 9 утра" },
  { id: 3, text_ua: "Реакція, коли приходить зарплата і відразу зникає", text_ru: "Реакция, когда приходит зарплата и сразу исчезает" },
  { id: 4, text_ua: "Я, коли кажу 'ще одне відео і спати'", text_ru: "Я, когда говорю 'ещё одно видео и спать'" },
  { id: 5, text_ua: "Коли вчитель каже 'це буде на іспиті'", text_ru: "Когда учитель говорит 'это будет на экзамене'" },
  { id: 6, text_ua: "Мої плани на вихідні vs реальність", text_ru: "Мои планы на выходные vs реальность" },
  { id: 7, text_ua: "Коли написав 'вже йду' але ще навіть не вдягнувся", text_ru: "Когда написал 'уже иду', но ещё даже не оделся" },
  { id: 8, text_ua: "Моя банківська карта після 'маленької покупки'", text_ru: "Моя карта после 'маленькой покупки'" },
  { id: 9, text_ua: "Коли всі хворі, а ти єдиний на роботі", text_ru: "Когда все болеют, а ты один на работе" },
  { id: 10, text_ua: "Реакція кота о 6 ранку на порожню миску", text_ru: "Реакция кота в 6 утра на пустую миску" },
  { id: 11, text_ua: "Коли прийшов на вечірку, а там тільки їжа", text_ru: "Когда пришёл на вечеринку, а там только еда" },
  { id: 12, text_ua: "Я пояснюю мем, який ніхто не зрозумів", text_ru: "Я объясняю мем, который никто не понял" },
  { id: 13, text_ua: "Коли твій інтернет вирубався під час важливої зустрічі", text_ru: "Когда интернет вырубился во время важной встречи" },
  { id: 14, text_ua: "Моє обличчя, коли бачу рахунок у ресторані", text_ru: "Моё лицо, когда вижу счёт в ресторане" },
  { id: 15, text_ua: "Коли намагаєшся виглядати зайнятим перед начальником", text_ru: "Когда пытаешься выглядеть занятым перед начальником" },
  { id: 16, text_ua: "Коли знайшов гроші в старій куртці", text_ru: "Когда нашёл деньги в старой куртке" },
  { id: 17, text_ua: "Моя сила волі перед тортом", text_ru: "Моя сила воли перед тортом" },
  { id: 18, text_ua: "Коли друг каже 'довірся мені'", text_ru: "Когда друг говорит 'доверься мне'" },
  { id: 19, text_ua: "Я після того як сказав 'я на дієті'", text_ru: "Я после того как сказал 'я на диете'" },
  { id: 20, text_ua: "Коли відкрив 47 вкладок і не знаєш яка з них грає музику", text_ru: "Когда открыл 47 вкладок и не знаешь какая играет музыку" },
  { id: 21, text_ua: "Моє 'ще 5 хвилин' о 7 ранку", text_ru: "Моё 'ещё 5 минут' в 7 утра" },
  { id: 22, text_ua: "Коли тебе додали в робочий чат о 23:00", text_ru: "Когда тебя добавили в рабочий чат в 23:00" },
  { id: 23, text_ua: "Моя реакція на 'нам треба поговорити'", text_ru: "Моя реакция на 'нам надо поговорить'" },
  { id: 24, text_ua: "Коли вимкнув будильник і 'тільки очі закрию'", text_ru: "Когда выключил будильник и 'только глаза закрою'" },
  { id: 25, text_ua: "Коли намагаєшся зрозуміти жарт через 5 секунд", text_ru: "Когда пытаешься понять шутку через 5 секунд" },
  { id: 26, text_ua: "Мій мозок о 3 ночі, коли треба спати", text_ru: "Мой мозг в 3 ночи, когда надо спать" },
  { id: 27, text_ua: "Коли обіцяв собі лягти рано", text_ru: "Когда обещал себе лечь рано" },
  { id: 28, text_ua: "Моє резюме vs мої реальні навички", text_ru: "Моё резюме vs мои реальные навыки" },
  { id: 29, text_ua: "Коли кажуть 'буде весело' — і це не весело", text_ru: "Когда говорят 'будет весело' — и это не весело" },
  { id: 30, text_ua: "Коли намагаєшся бути дорослим і відповідальним", text_ru: "Когда пытаешься быть взрослым и ответственным" },
  { id: 31, text_ua: "Моя продуктивність за день до дедлайну", text_ru: "Моя продуктивность за день до дедлайна" },
  { id: 32, text_ua: "Коли хтось каже 'ти ж програміст, почини принтер'", text_ru: "Когда кто-то говорит 'ты же программист, почини принтер'" },
  { id: 33, text_ua: "Коли замовив салат, а друзі — піцу", text_ru: "Когда заказал салат, а друзья — пиццу" },
  { id: 34, text_ua: "Моє обличчя на фото в паспорті", text_ru: "Моё лицо на фото в паспорте" },
  { id: 35, text_ua: "Коли вирішив 'з понеділка нове життя'", text_ru: "Когда решил 'с понедельника новая жизнь'" },
  { id: 36, text_ua: "Коли бачиш, що хтось пише і раптом перестає", text_ru: "Когда видишь, что кто-то пишет и вдруг перестаёт" },
  { id: 37, text_ua: "Мій абонемент у спортзал, який я відвідав двічі", text_ru: "Мой абонемент в спортзал, который я посетил дважды" },
  { id: 38, text_ua: "Коли офіціант питає 'все смачно?' з повним ротом", text_ru: "Когда официант спрашивает 'всё вкусно?' с полным ртом" },
  { id: 39, text_ua: "Коли твій план 'буду продуктивним' зустрів диван", text_ru: "Когда план 'буду продуктивным' встретил диван" },
  { id: 40, text_ua: "Коли кажеш 'я не голодний' і доїдаєш чужу тарілку", text_ru: "Когда говоришь 'я не голоден' и доедаешь чужую тарелку" },
  { id: 41, text_ua: "Я о 2 ночі гуглю симптоми звичайної застуди", text_ru: "Я в 2 ночи гуглю симптомы обычной простуды" },
  { id: 42, text_ua: "Коли поклав щось 'на надійне місце' і забув куди", text_ru: "Когда положил что-то 'в надёжное место' и забыл куда" },
  { id: 43, text_ua: "Моя мотивація після першої чашки кави", text_ru: "Моя мотивация после первой чашки кофе" },
  { id: 44, text_ua: "Коли всі мовчать, а в тебе бурчить живіт", text_ru: "Когда все молчат, а у тебя урчит живот" },
  { id: 45, text_ua: "Я вдаю, що слухаю, а сам думаю про обід", text_ru: "Я делаю вид, что слушаю, а сам думаю про обед" },
  { id: 46, text_ua: "Коли натиснув 'відповісти всім' замість 'відповісти'", text_ru: "Когда нажал 'ответить всем' вместо 'ответить'" },
  { id: 47, text_ua: "Моє обличчя, коли хтось псує кінцівку фільму", text_ru: "Моё лицо, когда кто-то спойлерит концовку фильма" },
  { id: 48, text_ua: "Коли зарядка телефона 1%, а ти далеко від розетки", text_ru: "Когда зарядка телефона 1%, а ты далеко от розетки" },
  { id: 49, text_ua: "Я після того як пообіцяв 'буду пити більше води'", text_ru: "Я после того как пообещал 'буду пить больше воды'" },
  { id: 50, text_ua: "Коли друзі обирають куди піти їсти вже годину", text_ru: "Когда друзья выбирают куда пойти есть уже час" },
  { id: 51, text_ua: "Моя поведінка в магазині з порожнім шлунком", text_ru: "Моё поведение в магазине на голодный желудок" },
  { id: 52, text_ua: "Коли побачив себе у відеодзвінку і злякався", text_ru: "Когда увидел себя в видеозвонке и испугался" },
  { id: 53, text_ua: "Я, коли треба прокинутись рано у вихідний без причини", text_ru: "Я, когда нужно проснуться рано в выходной без причины" },
  { id: 54, text_ua: "Коли хтось каже 'це легко, просто зроби'", text_ru: "Когда кто-то говорит 'это легко, просто сделай'" },
  { id: 55, text_ua: "Моя сила волі біля холодильника опівночі", text_ru: "Моя сила воли у холодильника в полночь" },
  { id: 56, text_ua: "Коли вдаєш, що зрозумів інструкцію, але ні", text_ru: "Когда делаешь вид, что понял инструкцию, но нет" },
  { id: 57, text_ua: "Я після 'ще одна серія і точно спати' о 3 ночі", text_ru: "Я после 'ещё одна серия и точно спать' в 3 ночи" },
  { id: 58, text_ua: "Коли в чаті всі активні, крім того хто мав відповісти", text_ru: "Когда в чате все активны, кроме того кто должен ответить" },
  { id: 59, text_ua: "Моя реакція на слово 'терміново' в листі від боса", text_ru: "Моя реакция на слово 'срочно' в письме от босса" },
  { id: 60, text_ua: "Коли намагаєшся тихо відкрити чіпси на парі", text_ru: "Когда пытаешься тихо открыть чипсы на паре" },
  { id: 61, text_ua: "Я, коли касир питає 'пакет потрібен?'", text_ru: "Я, когда кассир спрашивает 'пакет нужен?'" },
  { id: 62, text_ua: "Коли поставив таймер на 10 хвилин, а проспав годину", text_ru: "Когда поставил таймер на 10 минут, а проспал час" },
  { id: 63, text_ua: "Моє ставлення до понеділка vs до п'ятниці", text_ru: "Моё отношение к понедельнику vs к пятнице" },
  { id: 64, text_ua: "Коли кажеш 'останній келих' уже втретє", text_ru: "Когда говоришь 'последний бокал' уже в третий раз" },
  { id: 65, text_ua: "Я, коли треба представитись перед групою", text_ru: "Я, когда нужно представиться перед группой" },
  { id: 66, text_ua: "Коли пилосос налякав кота, а потім тебе", text_ru: "Когда пылесос напугал кота, а потом тебя" },
  { id: 67, text_ua: "Моя продуктивність коли ніхто не дивиться", text_ru: "Моя продуктивность когда никто не смотрит" },
  { id: 68, text_ua: "Коли хтось їсть голосно поруч у тиші", text_ru: "Когда кто-то ест громко рядом в тишине" },
  { id: 69, text_ua: "Я після того як сказав 'довірся, я знаю дорогу'", text_ru: "Я после того как сказал 'доверься, я знаю дорогу'" },
  { id: 70, text_ua: "Коли пишеш повідомлення, видаляєш і пишеш знову", text_ru: "Когда пишешь сообщение, удаляешь и пишешь снова" },
  { id: 71, text_ua: "Моє обличчя, коли план спрацював з першого разу", text_ru: "Моё лицо, когда план сработал с первого раза" },
  { id: 72, text_ua: "Коли намагаєшся вийти з розмови, а вона не закінчується", text_ru: "Когда пытаешься выйти из разговора, а он не заканчивается" },
  { id: 73, text_ua: "Я, коли бачу знижку на те, що мені не потрібно", text_ru: "Я, когда вижу скидку на то, что мне не нужно" },
  { id: 74, text_ua: "Коли всі вже на зустрічі, а ти шукаєш кнопку 'увімкнути мікрофон'", text_ru: "Когда все уже на встрече, а ты ищешь кнопку 'включить микрофон'" },
  { id: 75, text_ua: "Моя пам'ять, коли треба згадати чому я зайшов у кімнату", text_ru: "Моя память, когда нужно вспомнить зачем я зашёл в комнату" },
  { id: 76, text_ua: "Коли вдаєш зайнятість, бо начальник проходить повз", text_ru: "Когда делаешь вид, что занят, потому что начальник проходит мимо" },
  { id: 77, text_ua: "Я після того як натиснув 'відкласти будильник' 6 разів", text_ru: "Я после того как нажал 'отложить будильник' 6 раз" },
  { id: 78, text_ua: "Коли друг каже 'я майже готовий' і це означає ще годину", text_ru: "Когда друг говорит 'я почти готов' и это значит ещё час" },
  { id: 79, text_ua: "Моя реакція коли інтернет повертається після обриву", text_ru: "Моя реакция когда интернет возвращается после обрыва" },
  { id: 80, text_ua: "Коли намагаєшся виглядати нормально після того як спіткнувся", text_ru: "Когда пытаешься выглядеть нормально после того как споткнулся" },
]

export const MEME_CARDS: MemeCard[] = [
  { id: 1, title: "Drake Hotline Bling", image_url: "https://i.imgflip.com/30b1gx.jpg" },
  { id: 2, title: "Two Buttons", image_url: "https://i.imgflip.com/1g8my4.jpg" },
  { id: 3, title: "Distracted Boyfriend", image_url: "https://i.imgflip.com/1ur9b0.jpg" },
  { id: 4, title: "UNO Draw 25 Cards", image_url: "https://i.imgflip.com/3lmzyx.jpg" },
  { id: 5, title: "Left Exit 12 Off Ramp", image_url: "https://i.imgflip.com/22bdq6.jpg" },
  { id: 6, title: "Bernie Asking For Support", image_url: "https://i.imgflip.com/3oevdk.jpg" },
  { id: 7, title: "Running Away Balloon", image_url: "https://i.imgflip.com/261o3j.jpg" },
  { id: 8, title: "Always Has Been", image_url: "https://i.imgflip.com/46e43q.png" },
  { id: 9, title: "Waiting Skeleton", image_url: "https://i.imgflip.com/2fm6x.jpg" },
  { id: 10, title: "Gru's Plan", image_url: "https://i.imgflip.com/26jxvz.jpg" },
  { id: 11, title: "Epic Handshake", image_url: "https://i.imgflip.com/28j0te.jpg" },
  { id: 12, title: "Disaster Girl", image_url: "https://i.imgflip.com/23ls.jpg" },
  { id: 13, title: "Anakin Padme 4 Panel", image_url: "https://i.imgflip.com/5c7lwq.png" },
  { id: 14, title: "X, X Everywhere", image_url: "https://i.imgflip.com/1ihzfe.jpg" },
  { id: 15, title: "Sad Pablo Escobar", image_url: "https://i.imgflip.com/1c1uej.jpg" },
  { id: 16, title: "Change My Mind", image_url: "https://i.imgflip.com/24y43o.jpg" },
  { id: 17, title: "Woman Yelling At Cat", image_url: "https://i.imgflip.com/345v97.jpg" },
  { id: 18, title: "Mocking Spongebob", image_url: "https://i.imgflip.com/1otk96.jpg" },
  { id: 19, title: "Batman Slapping Robin", image_url: "https://i.imgflip.com/9ehk.jpg" },
  { id: 20, title: "Buff Doge vs. Cheems", image_url: "https://i.imgflip.com/43a45p.png" },
  { id: 21, title: "Expanding Brain", image_url: "https://i.imgflip.com/1jwhww.jpg" },
  { id: 22, title: "Trade Offer", image_url: "https://i.imgflip.com/54hjww.jpg" },
  { id: 23, title: "This Is Fine", image_url: "https://i.imgflip.com/wxica.jpg" },
  { id: 24, title: "Ancient Aliens", image_url: "https://i.imgflip.com/26am.jpg" },
  { id: 25, title: "Tuxedo Winnie The Pooh", image_url: "https://i.imgflip.com/2ybua0.png" },
  { id: 26, title: "Y'all Got Any More Of That", image_url: "https://i.imgflip.com/21uy0f.jpg" },
  { id: 27, title: "Absolute Cinema", image_url: "https://i.imgflip.com/8d317n.png" },
  { id: 28, title: "They're The Same Picture", image_url: "https://i.imgflip.com/2za3u1.jpg" },
  { id: 29, title: "One Does Not Simply", image_url: "https://i.imgflip.com/1bij.jpg" },
  { id: 30, title: "Monkey Puppet", image_url: "https://i.imgflip.com/2gnnjh.jpg" },
  { id: 31, title: "Is This A Pigeon", image_url: "https://i.imgflip.com/1o00in.jpg" },
  { id: 32, title: "Bike Fall", image_url: "https://i.imgflip.com/1b42wl.jpg" },
  { id: 33, title: "Put My Trophy If I Had One", image_url: "https://i.imgflip.com/1wz1x.jpg" },
  { id: 34, title: "You Guys Are Getting Paid", image_url: "https://i.imgflip.com/2xscjb.png" },
  { id: 35, title: "Clown Applying Makeup", image_url: "https://i.imgflip.com/38el31.jpg" },
  { id: 36, title: "Marked Safe From", image_url: "https://i.imgflip.com/2odckz.jpg" },
  { id: 37, title: "Megamind Peeking", image_url: "https://i.imgflip.com/64sz4u.png" },
  { id: 38, title: "Thinking About Other Women", image_url: "https://i.imgflip.com/1tl71a.jpg" },
  { id: 39, title: "Oprah You Get A", image_url: "https://i.imgflip.com/gtj5t.jpg" },
  { id: 40, title: "Evil Kermit", image_url: "https://i.imgflip.com/1e7ql7.jpg" },
  { id: 41, title: "Boardroom Meeting Suggestion", image_url: "https://i.imgflip.com/m78d.jpg" },
  { id: 42, title: "Panik Kalm Panik", image_url: "https://i.imgflip.com/3qqcim.png" },
  { id: 43, title: "Hide The Pain Harold", image_url: "https://i.imgflip.com/gk5el.jpg" },
  { id: 44, title: "Roll Safe Think About It", image_url: "https://i.imgflip.com/1h7in3.jpg" },
  { id: 45, title: "Surprised Pikachu", image_url: "https://i.imgflip.com/2kbn1e.jpg" },
  { id: 46, title: "Leonardo Dicaprio Cheers", image_url: "https://i.imgflip.com/39t1o.jpg" },
  { id: 47, title: "Blank Nut Button", image_url: "https://i.imgflip.com/1yxkcp.jpg" },
  { id: 48, title: "Pawn Stars Best I Can Do", image_url: "https://i.imgflip.com/19vcz0.jpg" },
  { id: 49, title: "Futurama Fry", image_url: "https://i.imgflip.com/1bgw.jpg" },
  { id: 50, title: "Sleeping Shaq", image_url: "https://i.imgflip.com/1nck6k.jpg" },
  { id: 51, title: "Squidward Window", image_url: "https://i.imgflip.com/145qvv.jpg" },
  { id: 52, title: "Imagination Spongebob", image_url: "https://i.imgflip.com/3i7p.jpg" },
  { id: 53, title: "Spider-Man Triple Pointing", image_url: "https://i.imgflip.com/3eqjd8.jpg" },
  { id: 54, title: "Bell Curve", image_url: "https://i.imgflip.com/8tw3vb.png" },
  { id: 55, title: "Soldier Protecting Sleeping Child", image_url: "https://i.imgflip.com/2tzo2k.jpg" },
  { id: 56, title: "Two Guys On A Bus", image_url: "https://i.imgflip.com/5v6gwj.jpg" },
  { id: 57, title: "Inhaling Seagull", image_url: "https://i.imgflip.com/1w7ygt.jpg" },
  { id: 58, title: "Flex Tape", image_url: "https://i.imgflip.com/2reqtg.png" },
  { id: 59, title: "Where Monkey", image_url: "https://i.imgflip.com/58eyvu.png" },
  { id: 60, title: "No - Yes", image_url: "https://i.imgflip.com/24zoa8.jpg" },
  { id: 61, title: "Third World Skeptical Kid", image_url: "https://i.imgflip.com/265k.jpg" },
  { id: 62, title: "Types Of Headaches", image_url: "https://i.imgflip.com/1yz6z4.jpg" },
  { id: 63, title: "Laughing Leo", image_url: "https://i.imgflip.com/4acd7j.png" },
  { id: 64, title: "They Don't Know", image_url: "https://i.imgflip.com/4pn1an.png" },
  { id: 65, title: "Friendship Ended", image_url: "https://i.imgflip.com/29v4rt.jpg" },
  { id: 66, title: "AJ Styles & Undertaker", image_url: "https://i.imgflip.com/3vfrmx.jpg" },
  { id: 67, title: "Three-Headed Dragon", image_url: "https://i.imgflip.com/33e92f.jpg" },
  { id: 68, title: "Two Paths", image_url: "https://i.imgflip.com/54d9lj.png" },
  { id: 69, title: "Grandma Finds The Internet", image_url: "https://i.imgflip.com/1bhw.jpg" },
  { id: 70, title: "Whisper And Goosebumps", image_url: "https://i.imgflip.com/1op9wy.jpg" },
  { id: 71, title: "Anime Girl Hiding From Terminator", image_url: "https://i.imgflip.com/3po4m7.jpg" },
  { id: 72, title: "Grant Gustin Over Grave", image_url: "https://i.imgflip.com/3nx72a.png" },
  { id: 73, title: "Who Killed Hannibal", image_url: "https://i.imgflip.com/28s2gu.jpg" },
  { id: 74, title: "The Scroll Of Truth", image_url: "https://i.imgflip.com/21tqf4.jpg" },
  { id: 75, title: "All My Homies Hate", image_url: "https://i.imgflip.com/3kwur5.jpg" },
  { id: 76, title: "Star Wars Yoda", image_url: "https://i.imgflip.com/8k0sa.jpg" },
  { id: 77, title: "Megamind No Bitches", image_url: "https://i.imgflip.com/65939r.jpg" },
  { id: 78, title: "Look At Me", image_url: "https://i.imgflip.com/hmt3v.jpg" },
  { id: 79, title: "Success Kid", image_url: "https://i.imgflip.com/1bhk.jpg" },
  { id: 80, title: "Spider-Man Pointing", image_url: "https://i.imgflip.com/1tkjq9.jpg" },
  { id: 81, title: "When My Opponent Is", image_url: "https://i.imgflip.com/5youx3.jpg" },
  { id: 82, title: "The Rock Driving", image_url: "https://i.imgflip.com/grr.jpg" },
  { id: 83, title: "Is This A Butterfly", image_url: "https://i.imgflip.com/2cjr7j.jpg" },
  { id: 84, title: "Finding Neverland", image_url: "https://i.imgflip.com/3pnmg.jpg" },
  { id: 85, title: "Scooby-Doo Mask Reveal", image_url: "https://i.imgflip.com/2eeunw.jpg" },
  { id: 86, title: "Say The Line Bart", image_url: "https://i.imgflip.com/176h0h.jpg" },
  { id: 87, title: "Yo Dawg Heard You", image_url: "https://i.imgflip.com/26hg.jpg" },
  { id: 88, title: "Domino Effect", image_url: "https://i.imgflip.com/2oo7h0.jpg" },
  { id: 89, title: "I'm The Captain Now", image_url: "https://i.imgflip.com/hlmst.jpg" },
  { id: 90, title: "American Chopper Argument", image_url: "https://i.imgflip.com/2896ro.jpg" },
]
