// Автозгенеровано tools/gen_seed.py — вбудована колода для ОФЛАЙН-гри (без сервера/БД).
// Ті самі дані, що й у apps/web/db/seed.sql. НЕ редагувати вручну — правити в gen_seed.py.
export type Situation = { id: number; text_ua: string; text_ru: string }
export type MemeCard = { id: number; title: string; image_url: string }

export const SITUATIONS: Situation[] = [
  { id: 1, text_ua: "Коли о третій ночі ти відкриваєш холодильник у п'ятий раз...", text_ru: "Когда в три ночи ты открываешь холодильник в пятый раз..." },
  { id: 2, text_ua: "Мій настрій в понеділок о 9 ранку", text_ru: "Моё настроение в понедельник в 9 утра" },
  { id: 3, text_ua: "Реакція, коли приходить зарплата і відразу зникає", text_ru: "Реакция, когда приходит зарплата и сразу исчезает" },
  { id: 4, text_ua: "Я, коли кажу 'ще одне відео і спати'", text_ru: "Я, когда говорю 'ещё одно видео и спать'" },
  { id: 5, text_ua: "Коли вчитель каже 'це буде на іспиті'", text_ru: "Когда учитель говорит 'это будет на экзамене'" },
  { id: 6, text_ua: "Мої плани на вихідні vs реальність", text_ru: "Мои планы на выходные vs реальность" },
  { id: 7, text_ua: "Коли написав 'вже йду' але ще навіть не вдягнувся", text_ru: "Когда написал 'уже иду', но ещё даже не оделся" },
  { id: 8, text_ua: "Моя банківська карта після 'маленької покупки'", text_ru: "Моя карта после 'маленькой покупки'" },
  { id: 9, text_ua: "Коли всі хворі, а ти єдиний на роботі", text_ru: "Когда все болеют, а ты один на работе" },
  { id: 10, text_ua: "Реакція кота о 6 ранку на порожню миску", text_ru: "Реакция кота в 6 утра на пустую миску" },
  { id: 11, text_ua: "Коли прийшов на вечірку, а там тільки їжа", text_ru: "Когда пришёл на вечеринку, а там только еда" },
  { id: 12, text_ua: "Я пояснюю мем, який ніхто не зрозумів", text_ru: "Я объясняю мем, который никто не понял" },
  { id: 13, text_ua: "Коли твій інтернет вирубався під час важливої зустрічі", text_ru: "Когда интернет вырубился во время важной встречи" },
  { id: 14, text_ua: "Моє обличчя, коли бачу рахунок у ресторані", text_ru: "Моё лицо, когда вижу счёт в ресторане" },
  { id: 15, text_ua: "Коли намагаєшся виглядати зайнятим перед начальником", text_ru: "Когда пытаешься выглядеть занятым перед начальником" },
  { id: 16, text_ua: "Коли знайшов гроші в старій куртці", text_ru: "Когда нашёл деньги в старой куртке" },
  { id: 17, text_ua: "Моя сила волі перед тортом", text_ru: "Моя сила воли перед тортом" },
  { id: 18, text_ua: "Коли друг каже 'довірся мені'", text_ru: "Когда друг говорит 'доверься мне'" },
  { id: 19, text_ua: "Я після того як сказав 'я на дієті'", text_ru: "Я после того как сказал 'я на диете'" },
  { id: 20, text_ua: "Коли відкрив 47 вкладок і не знаєш яка з них грає музику", text_ru: "Когда открыл 47 вкладок и не знаешь какая играет музыку" },
  { id: 21, text_ua: "Моє 'ще 5 хвилин' о 7 ранку", text_ru: "Моё 'ещё 5 минут' в 7 утра" },
  { id: 22, text_ua: "Коли тебе додали в робочий чат о 23:00", text_ru: "Когда тебя добавили в рабочий чат в 23:00" },
  { id: 23, text_ua: "Моя реакція на 'нам треба поговорити'", text_ru: "Моя реакция на 'нам надо поговорить'" },
  { id: 24, text_ua: "Коли вимкнув будильник і 'тільки очі закрию'", text_ru: "Когда выключил будильник и 'только глаза закрою'" },
  { id: 25, text_ua: "Коли намагаєшся зрозуміти жарт через 5 секунд", text_ru: "Когда пытаешься понять шутку через 5 секунд" },
  { id: 26, text_ua: "Мій мозок о 3 ночі, коли треба спати", text_ru: "Мой мозг в 3 ночи, когда надо спать" },
  { id: 27, text_ua: "Коли обіцяв собі лягти рано", text_ru: "Когда обещал себе лечь рано" },
  { id: 28, text_ua: "Моє резюме vs мої реальні навички", text_ru: "Моё резюме vs мои реальные навыки" },
  { id: 29, text_ua: "Коли кажуть 'буде весело' — і це не весело", text_ru: "Когда говорят 'будет весело' — и это не весело" },
  { id: 30, text_ua: "Коли намагаєшся бути дорослим і відповідальним", text_ru: "Когда пытаешься быть взрослым и ответственным" },
  { id: 31, text_ua: "Моя продуктивність за день до дедлайну", text_ru: "Моя продуктивность за день до дедлайна" },
  { id: 32, text_ua: "Коли хтось каже 'ти ж програміст, почини принтер'", text_ru: "Когда кто-то говорит 'ты же программист, почини принтер'" },
  { id: 33, text_ua: "Коли замовив салат, а друзі — піцу", text_ru: "Когда заказал салат, а друзья — пиццу" },
  { id: 34, text_ua: "Моє обличчя на фото в паспорті", text_ru: "Моё лицо на фото в паспорте" },
  { id: 35, text_ua: "Коли вирішив 'з понеділка нове життя'", text_ru: "Когда решил 'с понедельника новая жизнь'" },
  { id: 36, text_ua: "Коли бачиш, що хтось пише і раптом перестає", text_ru: "Когда видишь, что кто-то пишет и вдруг перестаёт" },
  { id: 37, text_ua: "Мій абонемент у спортзал, який я відвідав двічі", text_ru: "Мой абонемент в спортзал, который я посетил дважды" },
  { id: 38, text_ua: "Коли офіціант питає 'все смачно?' з повним ротом", text_ru: "Когда официант спрашивает 'всё вкусно?' с полным ртом" },
  { id: 39, text_ua: "Коли твій план 'буду продуктивним' зустрів диван", text_ru: "Когда план 'буду продуктивным' встретил диван" },
  { id: 40, text_ua: "Коли кажеш 'я не голодний' і доїдаєш чужу тарілку", text_ru: "Когда говоришь 'я не голоден' и доедаешь чужую тарелку" },
  { id: 41, text_ua: "Я о 2 ночі гуглю симптоми звичайної застуди", text_ru: "Я в 2 ночи гуглю симптомы обычной простуды" },
  { id: 42, text_ua: "Коли поклав щось 'на надійне місце' і забув куди", text_ru: "Когда положил что-то 'в надёжное место' и забыл куда" },
  { id: 43, text_ua: "Моя мотивація після першої чашки кави", text_ru: "Моя мотивация после первой чашки кофе" },
  { id: 44, text_ua: "Коли всі мовчать, а в тебе бурчить живіт", text_ru: "Когда все молчат, а у тебя урчит живот" },
  { id: 45, text_ua: "Я вдаю, що слухаю, а сам думаю про обід", text_ru: "Я делаю вид, что слушаю, а сам думаю про обед" },
  { id: 46, text_ua: "Коли натиснув 'відповісти всім' замість 'відповісти'", text_ru: "Когда нажал 'ответить всем' вместо 'ответить'" },
  { id: 47, text_ua: "Моє обличчя, коли хтось псує кінцівку фільму", text_ru: "Моё лицо, когда кто-то спойлерит концовку фильма" },
  { id: 48, text_ua: "Коли зарядка телефона 1%, а ти далеко від розетки", text_ru: "Когда зарядка телефона 1%, а ты далеко от розетки" },
  { id: 49, text_ua: "Я після того як пообіцяв 'буду пити більше води'", text_ru: "Я после того как пообещал 'буду пить больше воды'" },
  { id: 50, text_ua: "Коли друзі обирають куди піти їсти вже годину", text_ru: "Когда друзья выбирают куда пойти есть уже час" },
  { id: 51, text_ua: "Моя поведінка в магазині з порожнім шлунком", text_ru: "Моё поведение в магазине на голодный желудок" },
  { id: 52, text_ua: "Коли побачив себе у відеодзвінку і злякався", text_ru: "Когда увидел себя в видеозвонке и испугался" },
  { id: 53, text_ua: "Я, коли треба прокинутись рано у вихідний без причини", text_ru: "Я, когда нужно проснуться рано в выходной без причины" },
  { id: 54, text_ua: "Коли хтось каже 'це легко, просто зроби'", text_ru: "Когда кто-то говорит 'это легко, просто сделай'" },
  { id: 55, text_ua: "Моя сила волі біля холодильника опівночі", text_ru: "Моя сила воли у холодильника в полночь" },
  { id: 56, text_ua: "Коли вдаєш, що зрозумів інструкцію, але ні", text_ru: "Когда делаешь вид, что понял инструкцию, но нет" },
  { id: 57, text_ua: "Я після 'ще одна серія і точно спати' о 3 ночі", text_ru: "Я после 'ещё одна серия и точно спать' в 3 ночи" },
  { id: 58, text_ua: "Коли в чаті всі активні, крім того хто мав відповісти", text_ru: "Когда в чате все активны, кроме того кто должен ответить" },
  { id: 59, text_ua: "Моя реакція на слово 'терміново' в листі від боса", text_ru: "Моя реакция на слово 'срочно' в письме от босса" },
  { id: 60, text_ua: "Коли намагаєшся тихо відкрити чіпси на парі", text_ru: "Когда пытаешься тихо открыть чипсы на паре" },
  { id: 61, text_ua: "Я, коли касир питає 'пакет потрібен?'", text_ru: "Я, когда кассир спрашивает 'пакет нужен?'" },
  { id: 62, text_ua: "Коли поставив таймер на 10 хвилин, а проспав годину", text_ru: "Когда поставил таймер на 10 минут, а проспал час" },
  { id: 63, text_ua: "Моє ставлення до понеділка vs до п'ятниці", text_ru: "Моё отношение к понедельнику vs к пятнице" },
  { id: 64, text_ua: "Коли кажеш 'останній келих' уже втретє", text_ru: "Когда говоришь 'последний бокал' уже в третий раз" },
  { id: 65, text_ua: "Я, коли треба представитись перед групою", text_ru: "Я, когда нужно представиться перед группой" },
  { id: 66, text_ua: "Коли пилосос налякав кота, а потім тебе", text_ru: "Когда пылесос напугал кота, а потом тебя" },
  { id: 67, text_ua: "Моя продуктивність коли ніхто не дивиться", text_ru: "Моя продуктивность когда никто не смотрит" },
  { id: 68, text_ua: "Коли хтось їсть голосно поруч у тиші", text_ru: "Когда кто-то ест громко рядом в тишине" },
  { id: 69, text_ua: "Я після того як сказав 'довірся, я знаю дорогу'", text_ru: "Я после того как сказал 'доверься, я знаю дорогу'" },
  { id: 70, text_ua: "Коли пишеш повідомлення, видаляєш і пишеш знову", text_ru: "Когда пишешь сообщение, удаляешь и пишешь снова" },
  { id: 71, text_ua: "Моє обличчя, коли план спрацював з першого разу", text_ru: "Моё лицо, когда план сработал с первого раза" },
  { id: 72, text_ua: "Коли намагаєшся вийти з розмови, а вона не закінчується", text_ru: "Когда пытаешься выйти из разговора, а он не заканчивается" },
  { id: 73, text_ua: "Я, коли бачу знижку на те, що мені не потрібно", text_ru: "Я, когда вижу скидку на то, что мне не нужно" },
  { id: 74, text_ua: "Коли всі вже на зустрічі, а ти шукаєш кнопку 'увімкнути мікрофон'", text_ru: "Когда все уже на встрече, а ты ищешь кнопку 'включить микрофон'" },
  { id: 75, text_ua: "Моя пам'ять, коли треба згадати чому я зайшов у кімнату", text_ru: "Моя память, когда нужно вспомнить зачем я зашёл в комнату" },
  { id: 76, text_ua: "Коли вдаєш зайнятість, бо начальник проходить повз", text_ru: "Когда делаешь вид, что занят, потому что начальник проходит мимо" },
  { id: 77, text_ua: "Я після того як натиснув 'відкласти будильник' 6 разів", text_ru: "Я после того как нажал 'отложить будильник' 6 раз" },
  { id: 78, text_ua: "Коли друг каже 'я майже готовий' і це означає ще годину", text_ru: "Когда друг говорит 'я почти готов' и это значит ещё час" },
  { id: 79, text_ua: "Моя реакція коли інтернет повертається після обриву", text_ru: "Моя реакция когда интернет возвращается после обрыва" },
  { id: 80, text_ua: "Коли намагаєшся виглядати нормально після того як спіткнувся", text_ru: "Когда пытаешься выглядеть нормально после того как споткнулся" },
  { id: 81, text_ua: "Коли WiFi зник рівно на найцікавішому моменті", text_ru: "Когда WiFi пропал ровно на самом интересном моменте" },
  { id: 82, text_ua: "Моя реакція на 'ми ж домовлялись' коли нічого не пам'ятаю", text_ru: "Моя реакция на 'мы же договаривались' когда ничего не помню" },
  { id: 83, text_ua: "Коли мама каже 'ми вже виходимо' і проходить 40 хвилин", text_ru: "Когда мама говорит 'мы уже выходим' и проходит 40 минут" },
  { id: 84, text_ua: "Я під час дзвінка на якому можна було б просто написати", text_ru: "Я во время звонка, на котором можно было просто написать" },
  { id: 85, text_ua: "Коли намагаєшся поснідати, а вже час обідати", text_ru: "Когда пытаешься позавтракать, а уже время обедать" },
  { id: 86, text_ua: "Моє 'я не засну' о 9 вечора під серіальчик", text_ru: "Моё 'я не усну' в 9 вечера под сериальчик" },
  { id: 87, text_ua: "Коли всі навколо вже дорослі, а ти ще ні", text_ru: "Когда все вокруг уже взрослые, а ты ещё нет" },
  { id: 88, text_ua: "Моя впевненість після 'я все зрозумів' на лекції", text_ru: "Моя уверенность после 'я всё понял' на лекции" },
  { id: 89, text_ua: "Коли йдеш з магазину без пакету і все падає", text_ru: "Когда идёшь из магазина без пакета и всё падает" },
  { id: 90, text_ua: "Я після того як натиснув 'сплатити' не подивившись суму", text_ru: "Я после того как нажал 'оплатить' не глянув сумму" },
  { id: 91, text_ua: "Коли GPS каже 'розвернітесь' десятий раз підряд", text_ru: "Когда GPS говорит 'развернитесь' десятый раз подряд" },
  { id: 92, text_ua: "Мій кіт коли я працюю з дому: наглядач чи саботажник?", text_ru: "Мой кот когда я работаю из дома: надзиратель или саботажник?" },
  { id: 93, text_ua: "Коли написав 'зараз буду' а сам ще в пижамі", text_ru: "Когда написал 'сейчас буду' а сам ещё в пижаме" },
  { id: 94, text_ua: "Моя реакція на ціну авокадо у 2025", text_ru: "Моя реакция на цену авокадо в 2025" },
  { id: 95, text_ua: "Коли вмикаєш камеру на зумі і бачиш свій вигляд", text_ru: "Когда включаешь камеру на зуме и видишь свой вид" },
  { id: 96, text_ua: "Я перед тим як написати 'без проблем' маючи 99 проблем", text_ru: "Я перед тем как написать 'без проблем' имея 99 проблем" },
  { id: 97, text_ua: "Коли бабуся питає чому худий, хоча ти не худий", text_ru: "Когда бабушка спрашивает почему худой, хотя ты не худой" },
  { id: 98, text_ua: "Моя мотивація у понеділок vs у п'ятницю ввечері", text_ru: "Моя мотивация в понедельник vs в пятницу вечером" },
  { id: 99, text_ua: "Коли хтось повільно набирає повідомлення а потім стирає", text_ru: "Когда кто-то медленно набирает сообщение а потом стирает" },
  { id: 100, text_ua: "Я, коли кажу 'це мій останній мем на сьогодні'", text_ru: "Я, когда говорю 'это мой последний мем на сегодня'" },
  { id: 101, text_ua: "Коли дивишся фільм жахів і кажеш 'я б так не зробив'", text_ru: "Когда смотришь фильм ужасов и говоришь 'я бы так не сделал'" },
  { id: 102, text_ua: "Моя реакція коли хтось каже 'ти схожий на батька/маму'", text_ru: "Моя реакция когда кто-то говорит 'ты похож на отца/маму'" },
  { id: 103, text_ua: "Коли замовив онлайн одяг і він зовсім не такий як на фото", text_ru: "Когда заказал онлайн одежду и она совсем не такая как на фото" },
  { id: 104, text_ua: "Я, коли намагаюсь пояснити мем батькам", text_ru: "Я, когда пытаюсь объяснить мем родителям" },
  { id: 105, text_ua: "Коли в кіно хтось їсть попкорн голосніше за фільм", text_ru: "Когда в кино кто-то ест попкорн громче чем фильм" },
  { id: 106, text_ua: "Моє обличчя на робочому зумі vs в дзеркалі вдома", text_ru: "Моё лицо на рабочем зуме vs в зеркале дома" },
  { id: 107, text_ua: "Коли бабуся каже 'ти худий, їж' а ти щойно поїв", text_ru: "Когда бабушка говорит 'ты худой, ешь' а ты только что поел" },
  { id: 108, text_ua: "Я після перегляду мотиваційного відео в 2 ночі", text_ru: "Я после просмотра мотивационного видео в 2 ночи" },
  { id: 109, text_ua: "Коли друг каже 'я знаю коротку дорогу' і ви заблукали", text_ru: "Когда друг говорит 'я знаю короткую дорогу' и вы заблудились" },
  { id: 110, text_ua: "Моя впевненість перед іспитом vs під час іспиту", text_ru: "Моя уверенность перед экзаменом vs во время экзамена" },
  { id: 111, text_ua: "Коли хтось каже 'я не п'ю' а потім першим танцює на столі", text_ru: "Когда кто-то говорит 'я не пью' а потом первым танцует на столе" },
  { id: 112, text_ua: "Я, коли треба відповісти на повідомлення тижневої давнини", text_ru: "Я, когда надо ответить на сообщение недельной давности" },
  { id: 113, text_ua: "Коли ставиш на зарядку телефон і він показує 1%", text_ru: "Когда ставишь на зарядку телефон и он показывает 1%" },
  { id: 114, text_ua: "Моє ставлення до домашніх обов'язків в 20 vs в 30", text_ru: "Моё отношение к домашним обязанностям в 20 vs в 30" },
  { id: 115, text_ua: "Коли кажеш 'ок гугл' а телефон відповідає сірі", text_ru: "Когда говоришь 'ок гугл' а телефон отвечает сири" },
  { id: 116, text_ua: "Я, коли хтось питає 'а що ти робив цілий день'", text_ru: "Я, когда кто-то спрашивает 'а что ты делал весь день'" },
  { id: 117, text_ua: "Коли знайшов ідеальний мем але не знаєш кому послати", text_ru: "Когда нашёл идеальный мем но не знаешь кому послать" },
  { id: 118, text_ua: "Моя соціальна батарейка після 2 годин на вечірці", text_ru: "Моя социальная батарейка после 2 часов на вечеринке" },
  { id: 119, text_ua: "Коли хтось каже 'можу секунду?' і це тягнеться 20 хвилин", text_ru: "Когда кто-то говорит 'можно секунду?' и это тянется 20 минут" },
  { id: 120, text_ua: "Я перед дедлайном vs я коли дедлайн через місяць", text_ru: "Я перед дедлайном vs я когда дедлайн через месяц" },
]

export const MEME_CARDS: MemeCard[] = [
  { id: 1, title: "Drake Hotline Bling", image_url: "https://i.imgflip.com/30b1gx.jpg" },
  { id: 2, title: "Two Buttons", image_url: "https://i.imgflip.com/1g8my4.jpg" },
  { id: 3, title: "Distracted Boyfriend", image_url: "https://i.imgflip.com/1ur9b0.jpg" },
  { id: 4, title: "Left Exit 12 Off Ramp", image_url: "https://i.imgflip.com/22bdq6.jpg" },
  { id: 7, title: "Waiting Skeleton", image_url: "https://i.imgflip.com/2fm6x.jpg" },
  { id: 8, title: "Gru's Plan", image_url: "https://i.imgflip.com/26jxvz.jpg" },
  { id: 9, title: "Epic Handshake", image_url: "https://i.imgflip.com/28j0te.jpg" },
  { id: 10, title: "Disaster Girl", image_url: "https://i.imgflip.com/23ls.jpg" },
  { id: 12, title: "X, X Everywhere", image_url: "https://i.imgflip.com/1ihzfe.jpg" },
  { id: 14, title: "Woman Yelling At Cat", image_url: "https://i.imgflip.com/345v97.jpg" },
  { id: 15, title: "Mocking Spongebob", image_url: "https://i.imgflip.com/1otk96.jpg" },
  { id: 16, title: "Batman Slapping Robin", image_url: "https://i.imgflip.com/9ehk.jpg" },
  { id: 17, title: "Buff Doge vs. Cheems", image_url: "https://i.imgflip.com/43a45p.png" },
  { id: 18, title: "Expanding Brain", image_url: "https://i.imgflip.com/1jwhww.jpg" },
  { id: 19, title: "This Is Fine", image_url: "https://i.imgflip.com/wxica.jpg" },
  { id: 20, title: "Ancient Aliens", image_url: "https://i.imgflip.com/26am.jpg" },
  { id: 23, title: "Absolute Cinema", image_url: "https://i.imgflip.com/8d317n.png" },
  { id: 25, title: "One Does Not Simply", image_url: "https://i.imgflip.com/1bij.jpg" },
  { id: 26, title: "Monkey Puppet", image_url: "https://i.imgflip.com/2gnnjh.jpg" },
  { id: 30, title: "You Guys Are Getting Paid", image_url: "https://i.imgflip.com/2xscjb.png" },
  { id: 31, title: "Clown Applying Makeup", image_url: "https://i.imgflip.com/38el31.jpg" },
  { id: 32, title: "Megamind Peeking", image_url: "https://i.imgflip.com/64sz4u.png" },
  { id: 37, title: "Hide The Pain Harold", image_url: "https://i.imgflip.com/gk5el.jpg" },
  { id: 38, title: "Roll Safe Think About It", image_url: "https://i.imgflip.com/1h7in3.jpg" },
  { id: 40, title: "Leonardo Dicaprio Cheers", image_url: "https://i.imgflip.com/39t1o.jpg" },
  { id: 42, title: "Futurama Fry", image_url: "https://i.imgflip.com/1bgw.jpg" },
  { id: 44, title: "Squidward Window", image_url: "https://i.imgflip.com/145qvv.jpg" },
  { id: 45, title: "Imagination Spongebob", image_url: "https://i.imgflip.com/3i7p.jpg" },
  { id: 46, title: "Spider-Man Triple Pointing", image_url: "https://i.imgflip.com/3eqjd8.jpg" },
  { id: 48, title: "Two Guys On A Bus", image_url: "https://i.imgflip.com/5v6gwj.jpg" },
  { id: 50, title: "Where Monkey", image_url: "https://i.imgflip.com/58eyvu.png" },
  { id: 52, title: "Third World Skeptical Kid", image_url: "https://i.imgflip.com/265k.jpg" },
  { id: 53, title: "Laughing Leo", image_url: "https://i.imgflip.com/4acd7j.png" },
  { id: 57, title: "Three-Headed Dragon", image_url: "https://i.imgflip.com/33e92f.jpg" },
  { id: 59, title: "Grandma Finds The Internet", image_url: "https://i.imgflip.com/1bhw.jpg" },
  { id: 60, title: "Whisper And Goosebumps", image_url: "https://i.imgflip.com/1op9wy.jpg" },
  { id: 65, title: "Star Wars Yoda", image_url: "https://i.imgflip.com/8k0sa.jpg" },
  { id: 67, title: "Success Kid", image_url: "https://i.imgflip.com/1bhk.jpg" },
  { id: 68, title: "Spider-Man Pointing", image_url: "https://i.imgflip.com/1tkjq9.jpg" },
  { id: 74, title: "Yo Dawg Heard You", image_url: "https://i.imgflip.com/26hg.jpg" },
  { id: 76, title: "I'm The Captain Now", image_url: "https://i.imgflip.com/hlmst.jpg" },
  { id: 79, title: "Charlie Conspiracy (Always Sunny)", image_url: "https://i.imgflip.com/1itoun.jpg" },
  { id: 80, title: "Bugs Bunny Communist", image_url: "https://i.imgflip.com/44eggm.png" },
  { id: 81, title: "Mother Ignoring Drowning Kid", image_url: "https://i.imgflip.com/46hhvr.jpg" },
  { id: 82, title: "0 Days Without (Simpsons)", image_url: "https://i.imgflip.com/72epa9.png" },
  { id: 84, title: "Left Exit 12 Dual", image_url: "https://i.imgflip.com/4t0m5.jpg" },
  { id: 85, title: "Captain America Elevator", image_url: "https://i.imgflip.com/2wifvo.jpg" },
  { id: 86, title: "Willy Wonka Condescending", image_url: "https://i.imgflip.com/u94.jpg" },
  { id: 87, title: "Patrick Star Wallet", image_url: "https://i.imgflip.com/2p3dw0.jpg" },
  { id: 89, title: "Truman Show", image_url: "https://i.imgflip.com/95uyf8.jpg" },
  { id: 90, title: "But That's None Of My Business (Kermit)", image_url: "https://i.imgflip.com/9sw43.jpg" },
  { id: 91, title: "I'm Something Of A Scientist Myself", image_url: "https://i.imgflip.com/27qxmb.jpg" },
  { id: 92, title: "Grim Reaper Knocking Door", image_url: "https://i.imgflip.com/1qg8fp.jpg" },
  { id: 95, title: "Undertaker Sitting Up", image_url: "https://i.imgflip.com/49gdf9.jpg" },
  { id: 96, title: "Moe Throws Barney (Simpsons)", image_url: "https://i.imgflip.com/34eewo.jpg" },
  { id: 97, title: "SpongeBob Rainbow", image_url: "https://i.imgflip.com/jafn4.jpg" },
  { id: 101, title: "The Office Congratulations", image_url: "https://i.imgflip.com/2ji8hx.jpg" },
  { id: 102, title: "Kermit Window (Dark Side)", image_url: "https://i.imgflip.com/lukr1.jpg" },
  { id: 104, title: "Second Breakfast (LOTR)", image_url: "https://i.imgflip.com/7a9b3.jpg" },
  { id: 115, title: "Hold Fart", image_url: "https://i.imgflip.com/of959.jpg" },
  { id: 120, title: "Captain Picard Facepalm", image_url: "https://i.imgflip.com/wczz.jpg" },
  { id: 121, title: "Surprised Koala", image_url: "https://i.imgflip.com/ljk.jpg" },
  { id: 124, title: "Grumpy Cat", image_url: "https://i.imgflip.com/8p0a.jpg" },
  { id: 127, title: "Pepe The Frog", image_url: "https://i.imgflip.com/lntct.jpg" },
  { id: 129, title: "Who Wants To Be A Millionaire", image_url: "https://i.imgflip.com/2qkodw.jpg" },
  { id: 130, title: "Mr Bean Waiting", image_url: "https://i.imgflip.com/21ajtl.jpg" },
  { id: 131, title: "Dr Evil Laser (Austin Powers)", image_url: "https://i.imgflip.com/odluv.jpg" },
  { id: 132, title: "Cute Cat", image_url: "https://i.imgflip.com/4xgqu.jpg" },
  { id: 133, title: "Aaaaand Its Gone (South Park)", image_url: "https://i.imgflip.com/gft6.jpg" },
  { id: 134, title: "Steve Buscemi Fellow Kids", image_url: "https://i.imgflip.com/z2nqj.jpg" },
  { id: 135, title: "Don't You Squidward", image_url: "https://i.imgflip.com/26br.jpg" },
  { id: 136, title: "Dave Chappelle Modern Problems", image_url: "https://i.imgflip.com/k6jjl.jpg" },
  { id: 137, title: "SpongeBob Ight Imma Head Out", image_url: "https://i.imgflip.com/392xtu.jpg" },
  { id: 138, title: "Elmo Fire", image_url: "https://i.imgflip.com/2bqzyl.jpg" },
  { id: 139, title: "Avatar Guy Pointing (James Cameron)", image_url: "https://i.imgflip.com/7bv2j9.jpg" },
  { id: 140, title: "Woody And Buzz Everywhere", image_url: "https://i.imgflip.com/1c7cy8.jpg" },
  { id: 141, title: "Confession Bear", image_url: "https://i.imgflip.com/25wb.jpg" },
  { id: 142, title: "Soyboy Vs Yes Chad", image_url: "https://i.imgflip.com/3umnr3.jpg" },
  { id: 143, title: "Philosoraptor", image_url: "https://i.imgflip.com/1bgs.jpg" },
  { id: 144, title: "Laughing Men In Suits", image_url: "https://i.imgflip.com/jrj7.jpg" },
  { id: 146, title: "Satisfied Seal", image_url: "https://i.imgflip.com/e8gx0.jpg" },
  { id: 153, title: "Homer Simpson's Back Fat", image_url: "https://i.imgflip.com/2lhzmp.jpg" },
  { id: 154, title: "Smiling Cat", image_url: "https://i.imgflip.com/amuvy.jpg" },
  { id: 159, title: "Matrix Morpheus (What If I Told You)", image_url: "https://i.imgflip.com/25w3.jpg" },
  { id: 160, title: "Here's Johnny (The Shining)", image_url: "https://i.imgflip.com/6mk4.jpg" },
  { id: 164, title: "Patrick To Do List (SpongeBob)", image_url: "https://i.imgflip.com/43iacv.jpg" },
  { id: 165, title: "Red Pill Blue Pill (Matrix)", image_url: "https://i.imgflip.com/1e4lu0.jpg" },
  { id: 167, title: "Crying Cat", image_url: "https://i.imgflip.com/p0a19.jpg" },
  { id: 168, title: "Anthony Adams Rubbing Hands", image_url: "https://i.imgflip.com/391pr7.jpg" },
  { id: 170, title: "Traumatized Mr. Incredible", image_url: "https://i.imgflip.com/5mir21.jpg" },
  { id: 174, title: "Sweating Bullets", image_url: "https://i.imgflip.com/gx29i.jpg" },
  { id: 175, title: "Disappointed Man", image_url: "https://i.imgflip.com/3mkotw.jpg" },
  { id: 177, title: "Shut Up And Take My Money Fry", image_url: "https://i.imgflip.com/3si4.jpg" },
  { id: 183, title: "PTSD Chihuahua", image_url: "https://i.imgflip.com/39791a.jpg" },
  { id: 184, title: "Scared Cat", image_url: "https://i.imgflip.com/2hgfw.jpg" },
  { id: 185, title: "Narcos Waiting", image_url: "https://i.imgflip.com/28this.jpg" },
  { id: 186, title: "Giga Chad", image_url: "https://i.imgflip.com/35bdwf.jpg" },
  { id: 187, title: "Nick Young Confused", image_url: "https://i.imgflip.com/oqii0.jpg" },
  { id: 189, title: "Guy With Sand In Hands", image_url: "https://i.imgflip.com/vj2v8.jpg" },
  { id: 193, title: "Laughing Wolf", image_url: "https://i.imgflip.com/47fb8x.jpg" },
  { id: 195, title: "Willem Dafoe Looking Up", image_url: "https://i.imgflip.com/5blorg.jpg" },
  { id: 196, title: "Strong Dog vs Weak Dog", image_url: "https://i.imgflip.com/430rn7.jpg" },
  { id: 197, title: "Salt Bae", image_url: "https://i.imgflip.com/1hj6i2.jpg" },
  { id: 198, title: "Evil Toddler", image_url: "https://i.imgflip.com/51s5.jpg" },
  { id: 200, title: "Car Drift (Two Roads)", image_url: "https://i.imgflip.com/22modp.jpg" },
]
